language: android
dist: trusty
android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.3
    - android-29
    - extra-google-m2repository
    - extra-android-m2repository
before_install:
  - chmod a+x gradlew
script:
  - ./gradlew build
deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file_glob: true
  file: "/home/travis/build/alvisisme/android-demo/app/build/outputs/apk/*/*.apk"
  cleanup: true
  on:
    repo: alvisisme/android-demo
    all_branches: true
    tags: true
